# .github/workflows/deploy.yml
name: Deploy to DigitalOcean

on:
  push:
    branches:
      - test-ci # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: [self-hosted, linux, digitalocean]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy application
      run: |
        cd /home/aakash/gemini-todo-docker
        git pull origin test-ci
        npm install
        docker compose up -d
        echo "Deployment successful!"